server:
  port: 8080
  servlet:
    context-path: /blogSearch


spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/search;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
#REST API KEY
restApi:
  kakao:
    key: KakaoAK fe6d33f16dddc557ba78d0604946d058
    url:
      blogSearch: https://dapi.kakao.com/v2/search/blog
  naver:
    id: 06d_Igz7ML6N0u6KrrEM
    secret: lOUbG71yTp
    url:
      blogSearch: https://openapi.naver.com/v1/search/blog.json